version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi-1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - C:\Users\ruan_\OneDrive\Área de Trabalho\CursoJS\postgresdb:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
